modules/inscription/models/Postulant.php
<?php

namespace app\modules\inscription\models;

use Yii;
use app\modules\inscription\models\PostulantLiablePerson; 
use app\modules\fi\models\Academicperiods; 
use app\modules\fi\models\Program; 
use app\modules\fi\models\Shifts; 

/**
 * This is the model class for table "postulant".
 *
 * @property integer $id
 * @property string $first_name
 * @property string $last_name
 * @property string $gender
 * @property string $birthday
 * @property integer $cities
 * @property string $adresse
 * @property string $phone
 * @property integer $is_working
 * @property string $name_working
 * @property string $adress_working
 * @property string $work_phone
 * @property integer $apply_for_program
 * @property integer $program_second
 * @property integer $shift
 * @property string $last_class
 * @property string $previous_school
 * @property string $school_date_entry
 * @property double $last_average
 * @property integer $status
 * @property integer $academic_year
 * @property integer $cohorte
 * @property integer $recommandation_letter
 * @property string $exam_date
 * @property string $no_inscription
 * @property string $email
 * @property string $postulant_password
 * @property string $validation_code
 * @property integer $is_validation_expire
 * @property string $date_created
 * @property string $date_updated
 * @property string $create_by
 * @property string $update_by
 *
 * @property Academicperiods $academicYear
 * @property Program $applyForProgram
 * @property PostulantGrades[] $postulantGrades
 * @property PostulantLiablePerson[] $postulantLiablePeople
 * @property PostulantParent[] $postulantParents
 * @property PostulantSocial[] $postulantSocials
 */
class Postulant extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'postulant';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'gender', 'email', 'postulant_password', 'validation_code', 'is_validation_expire', 'date_created'], 'required'],
            [['birthday', 'school_date_entry', 'exam_date', 'date_created', 'date_updated'], 'safe'],
            [['cities', 'is_working', 'apply_for_program', 'program_second', 'shift', 'status', 'academic_year', 'cohorte', 'recommandation_letter', 'is_validation_expire'], 'integer'],
            [['name_working', 'adress_working', 'postulant_password'], 'string'],
            [['last_average'], 'number'],
            [['first_name'], 'string', 'max' => 120],
            [['last_name', 'gender', 'phone', 'create_by', 'update_by'], 'string', 'max' => 45],
            [['adresse', 'previous_school', 'email'], 'string', 'max' => 255],
            [['work_phone'], 'string', 'max' => 16],
            [['last_class'], 'string', 'max' => 64],
            [['no_inscription', 'validation_code'], 'string', 'max' => 32],
            [['email'], 'unique'],
            [['validation_code'], 'unique'],
            [['academic_year'], 'exist', 'skipOnError' => true, 'targetClass' => Academicperiods::className(), 'targetAttribute' => ['academic_year' => 'id']],
            [['apply_for_program'], 'exist', 'skipOnError' => true, 'targetClass' => Program::className(), 'targetAttribute' => ['apply_for_program' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'first_name' =>Yii::t('app','First Name'),
            'last_name' =>Yii::t('app','Last Name'),
            'gender' => 'Gender',
            'birthday' => 'Birthday',
            'cities' => 'Cities',
            'adresse' => 'Adresse',
            'phone' => 'Phone',
            'is_working' => 'Is Working',
            'name_working' => 'Name Working',
            'adress_working' => 'Adress Working',
            'work_phone' => 'Work Phone',
            'apply_for_program' => 'Apply For Program',
            'program_second' => 'Program Second',
            'shift' => 'Shift',
            'last_class' => 'Last Class',
            'previous_school' => 'Previous School',
            'school_date_entry' => 'School Date Entry',
            'last_average' => 'Last Average',
            'status' => 'Status',
            'academic_year' => 'Academic Year',
            'cohorte' => 'Cohorte',
            'recommandation_letter' => 'Recommandation Letter',
            'exam_date' => 'Exam Date',
            'no_inscription' => 'No Inscription',
            'email' => 'Email',
            'postulant_password' => 'Postulant Password',
            'validation_code' => 'Validation Code',
            'is_validation_expire' => 'Is Validation Expire',
            'date_created' => 'Date Created',
            'date_updated' => 'Date Updated',
            'create_by' => 'Create By',
            'update_by' => 'Update By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAcademicYear()
    {
        return $this->hasOne(Academicperiods::className(), ['id' => 'academic_year']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProgramSecond()
    {
        return $this->hasOne(Program::className(), ['id' => 'program_second']);
    }
    
    public function getApplyForProgram()
    {
        return $this->hasOne(Program::className(), ['id' => 'apply_for_program']);
    }
    
    public function getShift0()
    {
        return $this->hasOne(Shifts::className(), ['id' => 'shift']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPostulantGrades()
    {
        return $this->hasMany(PostulantGrades::className(), ['postulant' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPostulantLiablePeople()
    {
        return $this->hasMany(PostulantLiablePerson::className(), ['postulant' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPostulantParents()
    {
        return $this->hasMany(PostulantParent::className(), ['postulant' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPostulantSocials()
    {
        return $this->hasMany(PostulantSocial::className(), ['postulant' => 'id']);
    }
    
    public function getSexe(){
        if($this->gender == 0){
            return "Masculin";
        }elseif($this->gender==1){
            return "F&eacute;minin";
        }else{
            return "N/A";
        }
    }
    

    
    
}

modules/inscription/controllers/PostulantController.php
<?php

namespace app\modules\inscription\controllers;

use Yii;
use app\modules\inscription\models\Postulant;
use app\modules\inscription\models\SrcPostulant;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use app\modules\inscription\models\PostulantParent; 
use app\modules\inscription\models\PostulantLiablePerson;
use app\modules\inscription\models\PostulantHealth; 
use app\modules\inscription\models\PostulantSocial;
use app\modules\inscription\models\PostulantIncome;
use app\modules\inscription\models\PostulantGrades;
use app\modules\fi\models\YearMigrationCheck;
use app\modules\fi\models\SrcAcademicperiods;
use yii\helpers\Html;
use kartik\mpdf\Pdf; // For PDF 


/**
 * PostulantController implements the CRUD actions for Postulant model.
 */
class PostulantController extends Controller
{
    public $layout = "/inspinia";
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Postulant models.
     * @return mixed
     */
    public function actionIndex()
    {
        if(Yii::$app->user->can('inscription-postulant-index'))
         { 
            $searchModel = new SrcPostulant();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            $model = new Postulant(); 
            $payment = new PostulantIncome(); 
            $acad = Yii::$app->session['currentId_academic_year'];

            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'model'=>$model,
                'payment'=>$payment,
                'acad'=>$acad,
            ]);
         }
          else
        {
            if(Yii::$app->session['currentId_academic_year']=='')
              {   
              	  return $this->redirect(['/rbac/user/login']); 
                }
             else
               {  
              //throw new ForbiddenHttpException;
              Yii::$app->getSession()->setFlash('Error', [
                    'type' => 'danger', //  success,//  info,// warning,//  danger,//  growl,//   minimalist,//   pastel,//
                    'duration' =>120000,
                    'icon' => 'glyphicon glyphicon-exclamation-sign',      // glyphicon glyphicon-ok-sign // glyphicon glyphicon-info-sign // glyphicon glyphicon-exclamation-sign  //    glyphicon glyphicon-remove-sign 
                    'message' => Html::encode(Yii::t('app',"You do not have the privilleges to perform this action. Please contact the Direction !") ),
                    'title' => Html::encode(Yii::t('app','Unthorized access') ),
                    'positonY' => 'top',   //   top,//   bottom,//
                    'positonX' => 'center'    //   right,//   center,//  left,//
                ]);
              $this->redirect(Yii::$app->request->referrer);
               }

          }
    }
    
    public function actionReport(){
        $model = new Postulant();
        return $this->render('report',[
            'model'=>$model
        ]); 
    }
    
     public function actionExam()
    {
        if(Yii::$app->user->can('inscription-postulant-exam'))
         {   
            $date_debut_inscription = infoCmsConfig("date_debut_inscription");
        $searchModel = new SrcPostulant();
        $dataProvider = $searchModel->searchByDateStart($date_debut_inscription);  //search(Yii::$app->request->queryParams);
        $model = new Postulant(); 
        $payment = new PostulantIncome(); 
        $grades = new PostulantGrades(); 
        
        
        return $this->render('exam', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model'=>$model,
            'payment'=>$payment,
            'grades'=>$grades,
        ]);
         }
          else
        {
            if(Yii::$app->session['currentId_academic_year']=='')
              {   
              	  return $this->redirect(['/rbac/user/login']); 
                }
             else
               {  
              //throw new ForbiddenHttpException;
              Yii::$app->getSession()->setFlash('Error', [
                    'type' => 'danger', //  success,//  info,// warning,//  danger,//  growl,//   minimalist,//   pastel,//
                    'duration' =>120000,
                    'icon' => 'glyphicon glyphicon-exclamation-sign',      // glyphicon glyphicon-ok-sign // glyphicon glyphicon-info-sign // glyphicon glyphicon-exclamation-sign  //    glyphicon glyphicon-remove-sign 
                    'message' => Html::encode(Yii::t('app',"You do not have the privilleges to perform this action. Please contact the Direction !") ),
                    'title' => Html::encode(Yii::t('app','Unthorized access') ),
                    'positonY' => 'top',   //   top,//   bottom,//
                    'positonX' => 'center'    //   right,//   center,//  left,//
                ]);
              $this->redirect(Yii::$app->request->referrer);
               }

          }  
         

    }
    
    public function actionGrades()
    {
        if(Yii::$app->user->can('inscription-postulant-decision'))
         { 
           $date_debut_inscription = infoCmsConfig("date_debut_inscription");
        
           $program= '';
	        $shift= '';
                $is_save =0;
	        
                
           $searchModel = new SrcPostulant();
        $dataProvider = $searchModel->searchByProgrameShift($program,$shift,$date_debut_inscription);
           $model = new Postulant(); 
        
        if($model->load(Yii::$app->request->post()) ) 
	   {
                  if(isset($_POST['Postulant']['apply_for_program']))
	                { $program= $_POST['Postulant']['apply_for_program'];
	                  $model->apply_for_program=[$program];
	                }
	                
	                     if(isset($_POST['Postulant']['shift']))
		              { $shift= $_POST['Postulant']['shift'];
		                 $model->shift=[$shift]; 
		         
		              }
                              
        $dataProvider = $searchModel->searchByProgrameShift($program,$shift,$date_debut_inscription);
        
               if(isset($_POST['create'])){
                 
                    $ok=true;
	                    $model_new = new PostulantGrades();
	                   
					
					 $no_stud_has_grade=true;
			 	
                              
                                  	
                                     
                                 		   
				     foreach($_POST['id_grade'] as $id)
		                        {   	   
                                           if(isset($_POST['grades'][$id])&&($_POST['grades'][$id]!=''))
                                                $no_stud_has_grade=false;

                                        }
                                  
			             
					      if($no_stud_has_grade==false) // omwen 1 etidyan gen not
						    {   foreach($_POST['id_grade'] as $id)
						         {
						            
	                                  if(isset($_POST['grades'][$id]))
								                $grade=$_POST['grades'][$id];
											else
											 $grade=0;
											

		                                $model_new->setAttribute('postulant',$id);
		                                $model_new->setAttribute('program',$program);
                                                
                                                $postul = SrcPostulant::findOne($id);
                                                
                                                $model_new->setAttribute('academic_year',$postul->academic_year);
							            
							            
						                $model_new->setAttribute('grade_value',$grade);
									    
						                 $model_new->date_create=date('Y-m-d H:i:s');
						                $model_new->create_by=currentUser();
			
						                if($model_new->save() )
						                  { 
						                  	unset($model_new);
						                     $model_new = new PostulantGrades();
						                    
						                     $ok=true;
						                  	
						                  	}
					                 
					                      
						            
						            										   
								} 
						             
						      }
						    else 
						     { $ok=false;
						       Yii::$app->getSession()->setFlash('warning', [
										    'type' => 'warning', //  success,//  info,// warning,//  danger,//  growl,//   minimalist,//   pastel,//
										    'duration' => 36000,
										    'icon' => 'glyphicon glyphicon-exclamation-sign',      // glyphicon glyphicon-ok-sign // glyphicon glyphicon-info-sign // glyphicon glyphicon-exclamation-sign  //    glyphicon glyphicon-remove-sign 
										    'message' => Html::encode( Yii::t('app','You did not insert any grades.') ),
										    'title' => Html::encode(Yii::t('app','Warning') ),
										    'positonY' => 'top',   //   top,//   bottom,//
										    'positonX' => 'center'    //   right,//   center,//  left,//
										]);
						         //$model->apply_for_program='';
						     }
                                                     
                                                     
									
			               if ($ok==true) 
					          {  
                                                      $is_save =1;
                                                           
                                                           Yii::$app->getSession()->setFlash('success', [
										    'type' => 'success', //  success,//  info,// warning,//  danger,//  growl,//   minimalist,//   pastel,//
										    'duration' => 36000,

modules/inscription/views/postulant/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\inscription\models\SrcPostulant */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="postulant-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'first_name') ?>

    <?= $form->field($model, 'last_name') ?>

    <?= $form->field($model, 'gender') ?>

    <?= $form->field($model, 'birthday') ?>

    <?php // echo $form->field($model, 'cities') ?>

    <?php // echo $form->field($model, 'adresse') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'is_working') ?>

    <?php // echo $form->field($model, 'name_working') ?>

    <?php // echo $form->field($model, 'adress_working') ?>

    <?php // echo $form->field($model, 'apply_for_program') ?>

    <?php // echo $form->field($model, 'last_class') ?>

    <?php // echo $form->field($model, 'previous_school') ?>

    <?php // echo $form->field($model, 'school_date_entry') ?>

    <?php // echo $form->field($model, 'last_average') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'academic_year') ?>

    <?php // echo $form->field($model, 'cohorte') ?>

    <?php // echo $form->field($model, 'date_created') ?>

    <?php // echo $form->field($model, 'date_updated') ?>

    <?php // echo $form->field($model, 'create_by') ?>

    <?php // echo $form->field($model, 'update_by') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/inscription/views/postulant/choix2.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
use app\modules\fi\models\Program;

$program = Program::findBySql("SELECT id, label FROM program  WHERE is_special = 0 AND id <> $id")->all(); 
?>
<div class='form-group'>
        <label><strong>Deuxi&egrave;me choix de programme </strong></label>
        <br/>
        <select name='Postulant[second_program]' id='choix2' class='form-control'>
            <option>Choisir un programme</option>
        <?php 
            foreach($program as $p){
                ?>

            <option value='<?= $p->id; ?>'> <?= $p->label; ?></option>

            <?php 
            }
            ?>
        </select>
</div> 

modules/inscription/views/postulant/create.php
<?php 
    use yii\helpers\Html;
    $this->title = Yii::t('app', 'Create postulant');
?>

<?php // $this->render("//layouts/inscriptionLayout") ?>

<div class="row">
     <div class="" style="width:auto;float:left; margin-left:20px;">
            <?= Html::a('<i class="fa fa-plus"></i> ', ['../inscription/postulant/create','wh'=>'ap'], ['class' => 'btn btn-primary btn-sm','title'=>Yii::t('app','Add')]) ?> 
        
            
    </div>
    <div class="col-lg-6">
         <h3><?= $this->title; ?></h3>
     </div>
        
     
        
</div> 

<?php
        echo $this->render('_form', [
        'model' => $model,
        'liable'=>$liable,
        'payment'=>$payment,
    ]) ?>

modules/inscription/views/postulant/view-inscription.php
<?php
use app\modules\inscription\models\Postulant; 
use app\modules\inscription\models\PostulantLiablePerson; 
use app\modules\fi\models\Shifts; 
use app\modules\fi\models\Program;
use app\modules\fi\models\ProgramsLeaders;
use app\modules\fi\models\Persons;
use yii\widgets\ActiveForm;



/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

// echo $id;
setlocale(LC_TIME, 'fr','fr_FR','fr_FR@euro','fr_FR.utf8','fr-FR','fra');
$postulant = Postulant::findOne($id); 
$responsable = PostulantLiablePerson::findOne($responsable_id);
$all_program = Program::findAll(['is_special'=>0]);
$this->title = "Formulaire d'inscription de $postulant->first_name ".strtoupper($postulant->last_name);
$baseUrl = Yii::$app->request->BaseUrl;
$count_stud = Postulant::findBySql("SELECT * FROM postulant WHERE is_validation_expire = 3")->count();

$form = ActiveForm::begin(
                [
                    'options' => [
                        'id' => 'form-val-insc'
                    ]
                    ]
                ); 
?>


<div class='col-lg-1'>
</div>
<div class='col-lg-10'>
    
    
    
    
    <div id='espas-msg-valide'>
        
    </div>
<table id="w0" class="table table-striped table-bordered detail-view table-responsive">
    <tbody>
        <tr>
            <th><?= Yii::t('app','First name')?></th>
            <td>
             <a class='zonteks' data-type='text' data-name="prenom" data-pk="<?= $postulant->id;?>" data-url="update-inscription">    
            <?= $postulant->first_name; ?>
             </a>
             </td>
            <th><?= Yii::t('app','Last name')?></th>
            <td>
                <a class='zonteks' data-type='text' data-name="nom" data-pk="<?= $postulant->id;?>" data-url="update-inscription">
                    <?= $postulant->last_name; ?>
                </a>
            </td>
        </tr>
        <tr>
            <th><?= Yii::t('app','Gender');?></th>
            <td>
                <a class='zonteks' data-type='select' data-name="sexe" data-pk="<?= $postulant->id;?>" data-url="update-inscription" data-source="list-sexe">
                    <?= $postulant->sexe; ?>
                 </a>
            </td>
            <th><?=  Yii::t('app','Birthday');?></th>
            <td>
                <a class='zonteks' id="date-naissance" data-type="date" data-name="birthday" data-pk="<?= $postulant->id;?>" data-url="update-inscription">
                    <?php    Yii::$app->formatter->locale = 'fr-FR';?>
                    <?= Yii::$app->formatter->asDate($postulant->birthday); ?>
                </a>
            </td>
        </tr>
        <tr>
            <th><?= Yii::t('app','Shift');?></th>
            <td>
                <a class="zonteks" data-type="select" data-name="vacation" data-pk="<?= $postulant->id;?>" data-url="update-inscription"  data-source="list-shift">
                    <?= $postulant->shift0->shift_name; ?>
                </a>
            </td>
            <th><?= Yii::t('app','Program first choice');?></th>
            <td>
                <a class="zonteks" data-type="select" data-name="choix1" data-pk="<?= $postulant->id;?>" data-url="update-inscription" data-source="list-program">
                    <?= $postulant->applyForProgram->label; ?>
                </a>
            </td>
        </tr>
        <tr>
            <th><?= Yii::t('app','Program Second choice');?></th>
            <td>
                <a class="zonteks" data-type="select" data-name="choix2" data-pk="<?= $postulant->id;?>" data-url="update-inscription" data-source="list-program">
                    <?php
                    if(isset($postulant->programSecond->label)){
                        echo $postulant->programSecond->label; 
                    } else{
                        echo "";
                    }
                    ?>
                </a>
            </td>
            <th><?= Yii::t('app','Address in Port-au-Prince') ?></th>
            <td>
                <a class="zonteks" data-type="text" data-name="adresse" data-pk="<?= $postulant->id;?>" data-url="update-inscription">
                    <?= $postulant->adresse; ?>
                 </a>
            </td>
        </tr>
        <tr>
            <th><?= Yii::t('app','Phone');?></th>
            <td>
                <a class="zonteks" data-type="text" data-name="phone" data-pk="<?= $postulant->id;?>" data-url="update-inscription">
                    <?= $postulant->phone; ?>
                </a>
            </td>
            <th><?= Yii::t('app','Last school');?></th>
            <td>
                <a class="zonteks" data-type="text" data-name="school" data-pk="<?= $postulant->id;?>" data-url="update-inscription">
                    <?= $postulant->previous_school; ?>
                </a>
            </td>
        </tr>
        <tr>
            <th><?= Yii::t('app','Are you working ?')?></th>
            <td>
                <a  class="zonteks" data-type="select" data-name="working" data-pk="<?= $postulant->id;?>" data-url="update-inscription" data-source="list-bool">
                    <?php if($postulant->is_working==1){echo "Oui"; }else{ echo "Non"; } ?>
                </a>
            </td>
            <th><?= Yii::t('app','Email');?></th>
            <td>
                <a  class="zonteks" data-type="text" data-name="email" data-pk="<?= $postulant->id;?>" data-url="update-inscription" >
                    <?= $postulant->email ?>
                </a>
            </td>
        </tr>
        
        <tr>
            <th><?= Yii::t('app','Liable person first name') ?></th>
            <td>
                <a class="zonteks" data-type="text" data-name="responsable_prenom" data-pk="<?= $responsable->id;?>" data-url="update-inscription">
                    <?= $responsable->first_name; ?>
                </a>
            </td>
            <th><?= Yii::t('app','Liable person last name') ?></th>
            <td>
                <a class="zonteks" data-type="text" data-name="responsable_nom" data-pk="<?= $responsable->id;?>" data-url="update-inscription">
                    <?= strtoupper($responsable->last_name); ?>
                </a>
            </td>
        </tr>
        <tr>
            <th><?= Yii::t('app','Liable person address')?></th>
            <td>
                <a class="zonteks" data-type="text" data-name="responsable_adresse" data-pk="<?= $responsable->id;?>" data-url="update-inscription">
                    <?= $responsable->address; ?>
                </a>
            </td>
            <th><?= Yii::t('app','Liable person phone');?></th>
            <td>
                <a class="zonteks" data-type="text" data-name="responsable_phone" data-pk="<?= $responsable->id;?>" data-url="update-inscription">
                    <?= $responsable->phone; ?>
                </a>
            </td>
        </tr>
        <tr>
            <th><?= Yii::t('app','Liable person email');?></th>
            <td>
                <a class="zonteks" data-type="text" data-name="responsable_email" data-pk="<?= $responsable->id;?>" data-url="update-inscription">
                    <?= $responsable->email_responsable; ?>
                </a>
            </td>
            <th><?= Yii::t('app','Relation liable person')?></th>
            <td>
                <a class="zonteks" data-type="select" data-name="responsable_relation" data-pk="<?= $responsable->id;?>" data-url="update-inscription" data-source="list-relation">
                    <?php
                    if(isset($responsable->relation0->relation_name)){
                        echo $responsable->relation0->relation_name;
                    } else{
                        echo "";
                    }
                    
                    ?>
                 </a>
            </td>
        </tr>
        <tr>
            <th><?= Yii::t('app','Exam Date');?></th>
            <td>
                <a class='zonteks' id="date-naissance" data-type="date" data-name="exam_date" data-pk="<?= $postulant->id;?>" data-url="update-inscription">
                    <?php    Yii::$app->formatter->locale = 'fr-FR';?>
                    <?= Yii::$app->formatter->asDate($postulant->exam_date); ?>
                </a>
            </td>
        </tr>
    </tbody>
</table>
<?php if($postulant->is_validation_expire==2){ ?>
        <div class='col-xs-3'>
            <div class='input-group'>
                <input type='text' class='form-control' id='date-examen' placeholder="<?= Yii::t('app','Exam date'); ?>">
            </div> 
        </div>
        <a class='btn btn-google' id='valider-inscription' data-idpostulant='<?= $postulant->id;?>'> <?= Yii::t('app','Validate subscription for {name} subscription number {number}',['name'=>$postulant->first_name.' '.$postulant->last_name,'number'=>$postulant->id])?>
        </a>
        <a class='btn btn-primary' id='print-inscription' data-idpostulant='<?= $postulant->id;?>' href="<?= $baseUrl;?>/index.php/inscription/postulant/print-form?id=<?=$postulant->id; ?>" target="_new"> 
            <?= Yii::t('app','Print subscription for {name} subscription number {number}',['name'=>$postulant->first_name.' '.$postulant->last_name,'number'=>$postulant->id])?>
        </a>
        
    <?php }elseif($postulant->is_validation_expire == 3){ ?>
    <a class='btn btn-primary' id='print-inscription-2' data-idpostulant='<?= $postulant->id;?>' href="<?= $baseUrl;?>/index.php/inscription/postulant/print-form?id=<?=$postulant->id; ?>" target="_new"> 
        <?= Yii::t('app','Print subscription for {name} subscription number {number}',['name'=>$postulant->first_name.' '.$postulant->last_name,'number'=>$postulant->id])?>
     </a>
    <div class='alert alert-danger alert-dismissable'>
        <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
        
        <?= Yii::t('app','The subscription of {name} is already validate',['name'=>$postulant->first_name.' '.$postulant->last_name])?>
    </div>
    <?php } ?>    
    
</div>
<div class='col-lg-1'>
</div>


<?php ActiveForm::end(); ?>

 <p><br/><br/><br/><br/><br/><br/><br/></p>          
<?php
    
    $script = <<< JS
    $(document).ready(function(){
            $('#valider-inscription').show();
            $('#print-inscription').hide();
           $('.zonteks').editable(
                {
                'emptytext' : 'Ajouter',
                'mode'  : 'popup',
                showbuttons: true,
                
            }
            ); 
            
            $('#date-examen').datepicker({
                autoclose: true,
                dateFormat: 'dd-mm-yy'
            });
            
            $('#valider-inscription').click(function(){
                var id_postulant = $(this).attr('data-idpostulant');
                var date_examen = $('#date-examen').val();
                if(date_examen==''){
                        alert("La date d'examen est obligatoire !")
                    }else{
                $.post('$baseUrl/index.php/inscription/postulant/validate-inscription',{id_postulant:id_postulant,date_examen:date_examen},function(data){
                        $('#espas-msg-valide').html(data);
                        $('#valider-inscription').hide();
                        $('#print-inscription').show();
                    });
                }
                        //alert(id_postulant);
                });
            
        
      });

JS;
$this->registerJs($script);
?>            